name: Release Tooling
on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 22.13.0

permissions:
  contents: read # Restrict top-level permissions to read only

jobs:
  release-please:
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          config-file: .github/release-please/release-please-config.json
          manifest-file: .github/release-please/.release-please-manifest.json
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}

  deploy-storybook:
    permissions:
      pages: write
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          install_command: npm ci
          build_command: npm run build-storybook
          path: storybook-static
          checkout: false
